<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="../main.css">
    <title>Main</title>
</head>
<body>
<div class="container">
    <div id="main">
        <div id="left-column">

        </div>
        <div id="content">
            <div class="content-container">
                <div class="row">
                    <div class="header">Name</div>
                    <p>Value1</p>
                </div>
                <div class="row">
                    <div class="header">Status</div>
                    <p>Value1</p>
                </div>
                <div class="row">
                    <div class="header">Developer</div>
                    <p>Value1</p>
                    <p>Value1</p>
                </div>
            </div>
        </div>
        <div id="right-column">
            <a href="/login"><button type="button">Login</button></a>
        </div>
    </div>
</div>
<script src="../script.js"></script>
</body>
</html>